# Generated by Django 3.1.4 on 2022-01-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0002_auto_20220126_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-id',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='chef',
            options={'ordering': ('-id',), 'verbose_name': 'Chef', 'verbose_name_plural': 'Chefs'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('-id',), 'verbose_name': 'Orderitem', 'verbose_name_plural': 'Orderitems'},
        ),
    ]
