# Generated by Django 3.1.4 on 2022-01-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0003_auto_20220126_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='allocated',
            field=models.BooleanField(default=False),
        ),
    ]
