# Generated by Django 3.1.4 on 2022-01-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0004_orderitem_allocated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderitem_id', models.CharField(max_length=100)),
                ('orderitem_name', models.CharField(max_length=100)),
                ('orderitem_category', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('chef', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Allocation',
                'verbose_name_plural': 'Allocations',
                'ordering': ('-id',),
            },
        ),
    ]
