# Generated by Django 3.1.4 on 2022-02-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0008_allocation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='chef_image',
            field=models.ImageField(blank=True, null=True, upload_to='Chefs'),
        ),
    ]
